/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentationLayer;

import java.sql.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.WindowConstants;
import org.jfree.ui.RefineryUtilities;
import serviceLayer.CategoryServiceImplementation;
import serviceLayer.ItemServiceImplementation;
import serviceLayer.PredictionServiceImplementation;
import serviceLayer.SellsServiceImplementation;
import serviceLayer.interfaces.CategoryService;
import serviceLayer.interfaces.ItemService;
import serviceLayer.interfaces.PredictionService;
import serviceLayer.interfaces.SellsService;

/**
 *
 * @author AYUSH
 */
public class SaleForecastWindow extends javax.swing.JFrame {

    /**
     * Creates new form SaleForecastWindow
     */
    public SaleForecastWindow() {
        initComponents();
        initData();
    }
    
    public void initData() {
        CategoryService cs = new CategoryServiceImplementation();
        String[] catName = cs.getCatNames();
        // Getting String
        jComboBox1.setModel(new DefaultComboBoxModel(catName));
        jComboBox1.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Category");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Item");

        jButton1.setText("Calculate Profit by this Product For today");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(132, 132, 132))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(64, 64, 64))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(84, 84, 84)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        ItemService is  = new ItemServiceImplementation();
        if(jComboBox1.getSelectedItem() != null) {
            CategoryService cs = new CategoryServiceImplementation();
            int catId = cs.getId(jComboBox1.getSelectedItem().toString());
            String[] itemName = is.getItemNameWithStock(catId);
            jComboBox2.setModel(new DefaultComboBoxModel(itemName));
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(jComboBox1.getSelectedItem() != null && jComboBox2.getSelectedItem() != null) {
            CategoryService cs = new CategoryServiceImplementation();
            int catId = cs.getId(jComboBox1.getSelectedItem().toString());
            ItemService is = new ItemServiceImplementation();
            int itemId = is.getId(jComboBox2.getSelectedItem().toString());
            SellsService ss = new SellsServiceImplementation();
            java.util.Date currentDay = new java.util.Date();
            Date date = new Date(currentDay.getTime());
            int num = ss.getNum(itemId, date);
            double price = is.getPrice(itemId);
            int frequency = is.getFrequency(itemId);
            System.out.println(catId);
            System.out.println(itemId);
            System.out.println(num);
            System.out.println(price);
            System.out.println(frequency);
            double[] x1 = {1,catId,itemId,num,price,frequency};
            PredictionService ps = new PredictionServiceImplementation();
            double y1 = ps.calculateProfit(x1);
            double[] yi = new double[7];
            PredictionGraph pg = new PredictionGraph("Prediction Graph", "Orders vs Profit",y1,itemId);
            pg.setDefaultCloseOperation(pg.DISPOSE_ON_CLOSE);
            pg.pack();
            RefineryUtilities.centerFrameOnScreen(pg);
            pg.setVisible( true );
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
